### ISSUE TITLE
Error: failed to download "helm-consensys/qkm" (hint: running `helm repo update` may help) ```

### ISSUE THREAD

**Issue by andyafene** [ConsenSys/quorum-key-manager-helm#30]
**Context:**
```
helm version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

Hi ,

I'm trying to To install the chart with the release name qkm but I have the following issues:
```
helm install qkm helm-consensys/qkm 
Error: failed to download "helm-consensys/qkm" (hint: running `helm repo update` may help)
```
I tried the command  ```helm repo update``` but I still have the error message.

Can you help me? please

**Comment by iris-garcia** [comment]
Hi @andyafene, 

I think the documentation is not updated and the Helm chart name is `quorumkeymanager` instead, so the install should look like this:

```
helm install qkm helm-consensys/quorumkeymanager
```

A PR has been created to amend the documentation.

**Comment by 6l20** [comment]
Hi @andyafene,

Maybe you should take a look at this k8s example to help you quick-start a deployment with the options you prefer.
https://github.com/ConsenSys/quorum-key-manager-kubernetes
It is indeed possible to disable TLS if you wish

**Comment by andyafene** [comment]
Thank you very much @6120!
